name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Versions
        run: |
          echo Node:
          node --version
          echo NPM:
          npm --version
      - name: NPM audit
        run: npm audit
      - name: NPM install (ci)
        run: npm ci
      - name: Build
        run: npm run build
      - name: Flow
        run: npx flow
      - name: Test
        run: npm test
      - name: Archive build artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ format('build-{0}', matrix.node-version) }}
          path: build
  deploy-master:
    name: Deploy master
    needs: build
    runs-on: ubuntu-18.04
    if: (github.repository == 'codelearncreate/c2lc-coding-environment') && (github.ref == 'refs/heads/master') && (github.event_name == 'push')
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/download-artifact@v1
        with:
          name: build-10.x
          path: build
      - uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
